---
title: "Peng’s Exploratory Data Analysis Checklist"
output: html_document
date: "2024-03-04"
---

There are 10 steps in Peng's Exploratory Data Analysis Checklist. This worksheet will walk you through each step. 

## 1. FORMULATE YOUR QUESTION

```{r}
#Which states had the largest number of locations mapped in the GayGuides? 
```


## 2. READ IN YOUR DATA

```{r}
library(DigitalMethodsData)
data("gayguides")
```


## 3. CHECK THE PACKAGING

```{r}
nrow(gayguides)
ncol(gayguides)
```


## 4. RUN str()

```{r}
str(gayguides)
#making sure the numbers are "num"s and strings are "chr"s
```

## 5. LOOK AT THE TOP AND BOTTOM OF YOUR DATA

```{r}
head(gayguides)
```
```{r}
tail(gayguides)
```

## 6. CHECK YOUR "n"'S
```{r}
select(gayguides, state) %>% unique %>% nrow
```
```{r}
unique(gayguides$state)
#here we see that various abbreviations for DC, provinces, and Mexico inflate the number of states from 51 to 57. 
```

## 7. VALIDATE WITH ATLEAST ONE EXTERNAL SOURCE
```{r}
(gayguides[68, c(5, 8:9, 12:13)])
#Looking for the below lat and long
#32.79533055538653, -116.96098980394923
```

## 8. TRY THE EASY SOLUTION FIRST 
```{r}
library(plyr)
count(gayguides$state) %>% arrange(desc(freq))
```


## 9. CHALLENGE YOUR SOLUTION
```{r}
#perhaps locations in CA were logged for more years than those in NY or elsewhere
gayguides %>% 
    select(state, Year) %>%
  filter(state == "CA" | state == "NY") %>%  filter(Year == 1965:1985)  %>%
    group_by(state, Year) %>%
    arrange(desc(Year)) 

```


## 10. FOLLOW UP
```{r}
#Do you have the right data?
#This data has plenty of avenues to explore, and I do think it is well suited for the question I asked. According to the Gay Guides, California led the other states in numbers-of-locations by a significant margin, followed by New York. Florida and Texas coming in a third and fourth is interesting. 

#Do you need other data?
#I wonder how comprehensive the Gay Guides were. If there was another guide that maps this same kind of information, it would be interesting to cross-reference the two sources. 

#Do you have the right question? 
#Yes, but now I have more questions to ask. Namely, what cities in Florida and Texas led to them ranking so high in my results? 
```













